# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

ZSH_THEME="bean"
export POWERLINE_NO_SHELL_PROMPT=1

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"


# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker last-working-dir)

# User configuration
export XDG_CONFIG_HOME="$HOME/.config"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin"

source $ZSH/oh-my-zsh.sh

default_go_path="$HOME/go"

export GOPATH="$default_go_path"
export GOBIN="$HOME/go/bin"

export EDITOR=vim
export UBER_HOME="$HOME/uber"
export UBER_OWNER="bean@uber.com"

# custom bean setup for uber dev env
export DEFAULT_VIRTUAL_ENV_DIR=env

######## Alias Section ############################



# brew install zsh-syntax-highlighting
# https://gist.github.com/kevin-smets/8568070
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# custom terminal status
source ${HOME}/.zsh/rc.d/terminal_status
# handles directory profiles that allow exporting or changing things based on directory
source ${HOME}/.zsh/rc.d/dir_profiles
# set of functions to make things easier
source ${HOME}/.zsh/rc.d/quick_functions


# arc auto complete
source /usr/local/Cellar/arcanist/tip/arcanist/resources/shell/bash-completion

# auto-jump plugin - "j <dir>"
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

path=(/usr/local/sbin /usr/local/bin $path)

export POWERLINE_CONFIG_COMMAND="${HOME}/Virtualenvs/tmux-plugins/bin/powerline-config"
source "${HOME}/Virtualenvs/tmux-plugins/lib/python3.9/site-packages/powerline/bindings/zsh/powerline.zsh"

echo -e "`date +"%Y-%m-%d %H:%M:%S"` direnv hooking zsh"
eval "$(direnv hook zsh)"

autoload bashcompinit
bashcompinit

