cask_args appdir: "/Applications"

brew 'git'
brew 'grep'

brew 'zsh'
# used in the zsh configuration
brew "zsh-syntax-highlighting"
# this is for the autojump command we setup in our shell profile
brew "autojump"

# local tooling
brew 'direnv'

# tmux
brew 'tmux'
brew 'reattach-to-user-namespace'

## powerline deps
brew 'python'
brew 'coreutils'

cask 'spectacle'
